project:
  type: website

website:
  #logo: 
  title: "Fang Yuan Zhu"
  navbar:
    pinned: true
    #background: success
    #foreground: primary
    left:
      - text: Work Ex
        href: workEX/workEX.qmd
      - text: Project
        href: project/Project.qmd
      - text: Resume
        href: resume/Resume.qmd
      - text: Author
        href: about.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/zhu-fangyuan/
      - icon: github
        href: https://github.com/zhufy3
      
      


format:
  html:
    #code-fold: true
    #code-summary: "Show the code"
    #code-tools: true
    #code-block-bg: true
    #code-block-border-left: "bisque3"
    theme: 
      light: flatly
      dark: darkly
    #css: styles.css
    toc: false
    #toc-location: left


editor: visual


